name: Deploy frontend

on: workflow_call

#Примерные степы как может выглядеть пайплайн фронта
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build frontend
        run: echo Собирается билд бекенда /(прогоняются юнит тесты и запускаются линтеры при сборке/), формируется и публикуется Docker образ


  deploy-stage:
    needs: test
    run-on: ubuntu-latest
    steps:
      - name: Deploy frontend to stage/review app
        run: echo Происходит деплой фронта
